FROM node:lts-alpine
LABEL maintainer="clamp <imclamp@foxmail.com>"
ARG ASM_SCRIPTS_URL=https://github.com/DJ-clamp/BaseSation
ARG ASM_SCRIPTS_BRANCH=azmodan
ARG ASM_WRAPPER_URL=https://github.com/DJ-clamp/asm-wrapper
ARG ASM_WRAPPER_BRANCH=main
ARG enable_unicom=true
ENV PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
    LANG=zh_CN.UTF-8 \
    SHELL=/bin/bash \
    PS1="\u@\h:\w \$ " \
    ASM_SCRIPTS_BRANCH=azmodan \
    ASM_DIR=/AutoSignMachine
# install graphicsmagick from source because install via apk not working
ENV PKGNAME=graphicsmagick
ENV PKGVER=1.3.35
ENV PKGSOURCE=http://downloads.sourceforge.net/$PKGNAME/$PKGNAME/$PKGVER/GraphicsMagick-$PKGVER.tar.lz
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories \
    && apk update -f \
    && apk upgrade \
    && apk --no-cache add -f bash \
    coreutils \
    moreutils \
    git \
    wget \
    curl \
    nano \
    tzdata \
    perl \
    openssl \
    gcc \
    g++ \
    ffmpeg \
    libjpeg-turbo-dev \
    libpng-dev \
    libtool \
    libgomp \
    tesseract-ocr \
    &&  wget $PKGSOURCE \
    && lzip -d -c GraphicsMagick-$PKGVER.tar.lz | tar -xvf - \
    && cd GraphicsMagick-$PKGVER && \
    ./configure \
      --build=$CBUILD \
      --host=$CHOST \
      --prefix=/usr \
      --sysconfdir=/etc \
      --mandir=/usr/share/man \
      --infodir=/usr/share/info \
      --localstatedir=/var \
      --enable-shared \
      --disable-static \
      --with-modules \
      --with-threads \
      --with-gs-font-dir=/usr/share/fonts/Type1 \
      --with-quantum-depth=16 && \
    make && \
    make install && \
    cd / && \
    rm -rf GraphicsMagick-$PKGVER && \
    rm GraphicsMagick-$PKGVER.tar.lz \
    && rm -rf /var/cache/apk/* \
    && ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
    && echo "Asia/Shanghai" > /etc/timezone \
    && git clone -b ${ASM_WRAPPER_BRANCH} ${ASM_WRAPPER_URL} ${ASM_DIR} \
    && git clone -b ${ASM_SCRIPTS_BRANCH} ${ASM_SCRIPTS_URL} ${ASM_DIR}/scripts \
    && cd ${ASM_DIR}/scripts \
    && npm install \
    && cp -f ${ASM_DIR}/docker/entrypoint.sh /entrypoint.sh \
    && chmod 777 /entrypoint.sh

WORKDIR ${ASM_DIR}
ENTRYPOINT /entrypoint.sh